from enum import StrEnum


class ErrorCode(StrEnum):
    CLIENT_ERROR = "client_error"
    NOT_FOUND = "not_found"
    METHOD_NOT_ALLOWED = "method_not_allowed"
    TOO_MANY_FILES = "too_many_files"
    FILE_TOO_LARGE = "file_too_large"
    UNSUPPORTED_FILE_TYPE = "unsupported_file_type"
    EMPTY_FILE = "empty_file"
    INVALID_GENERATE_INPUT = "invalid_generate_input"
    CONTENT_GENERATION_FAILED = "content_generation_failed"
    INVALID_MODEL_OUTPUT = "invalid_model_output"
    MODEL_EMPTY_OUTPUT = "model_empty_output"
    REFINE_FAILED = "refine_failed"
    BACKEND_AUTH_NOT_CONFIGURED = "backend_auth_not_configured"
    UNAUTHORIZED = "unauthorized"
    DRAFT_NOT_FOUND = "draft_not_found"
    FILE_NOT_FOUND = "file_not_found"
    SOCIAL_AUTH_NOT_CONFIGURED = "social_auth_not_configured"
    SOCIAL_CONNECTION_NOT_FOUND = "social_connection_not_found"
    SOCIAL_CONNECTION_CONFLICT = "social_connection_conflict"
    INVALID_PUBLICATION_INPUT = "invalid_publication_input"
    PUBLICATION_NOT_FOUND = "publication_not_found"
    SOCIAL_PUBLISH_FAILED = "social_publish_failed"
    UNSUPPORTED_ASSET_TYPE = "unsupported_asset_type"
    TOO_MANY_ASSETS = "too_many_assets"
    SOCIAL_CONNECTION_INVALID = "social_connection_invalid"
    SOCIAL_TOKEN_EXPIRED = "social_token_expired"
    PROVIDER_RATE_LIMITED = "provider_rate_limited"
    AI_EXECUTION_NOT_FOUND = "ai_execution_not_found"
    INTERNAL_SERVER_ERROR = "internal_server_error"
